server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: discovery

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.autoconfigure.security: ERROR
